"""init_legal_schema

Revision ID: 98789af4c4dc
Revises: 857e2741406f
Create Date: 2026-07-23 22:49:47.765575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98789af4c4dc'
down_revision: Union[str, Sequence[str], None] = '857e2741406f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('name', sa.String(length=200), nullable=False, comment='渠道名称，如：12315消费者投诉热线'),
    sa.Column('domain', sa.String(length=100), nullable=False, comment='主要适用法律领域，如：consumer_market'),
    sa.Column('channel_type', sa.String(length=50), nullable=False, comment='渠道类型：hotline/website/app'),
    sa.Column('phone', sa.String(length=50), nullable=True, comment='联系电话（contacts 中 kind=phone 的第一条）'),
    sa.Column('url', sa.String(length=500), nullable=True, comment='官方网址（contacts 中 kind=website 的第一条）'),
    sa.Column('region_code', sa.String(length=20), nullable=False, comment='地区代码：CN=国家级 / BJ=北京 / SH=上海 等'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_channels_domain', 'channels', ['domain'], unique=False)
    op.create_index('ix_channels_region', 'channels', ['region_code'], unique=False)
    op.create_table('laws',
    sa.Column('title', sa.String(length=300), nullable=False, comment='法律全称，如：中华人民共和国劳动法'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='类别：法律/行政法规/司法解释'),
    sa.Column('authority', sa.String(length=200), nullable=True, comment='发布机关，如：全国人民代表大会常务委员会'),
    sa.Column('domain', sa.String(length=100), nullable=False, comment='法律领域，如：labor_social_security'),
    sa.Column('effective_from', sa.String(length=20), nullable=True, comment='施行日期，格式 YYYY-MM-DD'),
    sa.Column('file_path', sa.String(length=500), nullable=True, comment='本地 docx/pdf 相对路径'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_laws_domain', 'laws', ['domain'], unique=False)
    op.create_index('ix_laws_title', 'laws', ['title'], unique=False)
    op.create_table('legal_cases',
    sa.Column('facts', sa.Text(), nullable=False, comment='案件事实描述（CAIL: A/B/C 文本；concrete: 判决正文）'),
    sa.Column('domain', sa.String(length=100), nullable=False, comment='法律领域，如：criminal_public_security'),
    sa.Column('source', sa.String(length=50), nullable=False, comment='数据来源标签：cail2019_scm / concrete'),
    sa.Column('title', sa.String(length=300), nullable=True, comment='案件名称（concrete 有，CAIL 无）'),
    sa.Column('cause', sa.String(length=200), nullable=True, comment='案由，如：劳动争议 / 买卖合同纠纷'),
    sa.Column('court', sa.String(length=200), nullable=True, comment='审理法院'),
    sa.Column('gist', sa.Text(), nullable=True, comment='裁判要旨（concrete 有，CAIL 无）'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_legal_cases_domain', 'legal_cases', ['domain'], unique=False)
    op.create_index('ix_legal_cases_source', 'legal_cases', ['source'], unique=False)
    op.create_table('users',
    sa.Column('name', sa.String(length=100), nullable=False, comment='用户姓名'),
    sa.Column('gender', sa.String(length=10), nullable=True, comment='性别：男/女'),
    sa.Column('age', sa.Integer(), nullable=True, comment='年龄'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='联系电话'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_name', 'users', ['name'], unique=False)
    op.create_table('articles',
    sa.Column('law_id', sa.BigInteger(), nullable=False, comment='所属法律 ID'),
    sa.Column('article_no', sa.String(length=50), nullable=False, comment='条号，如：第一条 / 第二十三条'),
    sa.Column('content', sa.Text(), nullable=False, comment='条文正文'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['law_id'], ['laws.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_articles_law', 'articles', ['law_id'], unique=False)
    op.create_index('ix_articles_no', 'articles', ['article_no'], unique=False)
    op.create_table('law_cases',
    sa.Column('law_id', sa.BigInteger(), nullable=False, comment='法律 ID'),
    sa.Column('case_id', sa.BigInteger(), nullable=False, comment='案例 ID'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['case_id'], ['legal_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['law_id'], ['laws.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_law_cases_case', 'law_cases', ['case_id'], unique=False)
    op.create_index('ix_law_cases_law', 'law_cases', ['law_id'], unique=False)
    # drop child/junction tables before parents to avoid FK violations
    op.drop_table('drug_details')
    op.drop_index(op.f('ix_disease_drugs_disease'), table_name='disease_drugs')
    op.drop_index(op.f('ix_disease_drugs_drug'), table_name='disease_drugs')
    op.drop_table('disease_drugs')
    op.drop_index(op.f('ix_disease_symptoms_disease'), table_name='disease_symptoms')
    op.drop_index(op.f('ix_disease_symptoms_symptom'), table_name='disease_symptoms')
    op.drop_table('disease_symptoms')
    op.drop_index(op.f('ix_diseases_name'), table_name='diseases')
    op.drop_table('diseases')
    op.drop_index(op.f('ix_drugs_category'), table_name='drugs')
    op.drop_index(op.f('ix_drugs_name'), table_name='drugs')
    op.drop_table('drugs')
    op.drop_index(op.f('ix_symptoms_name'), table_name='symptoms')
    op.drop_table('symptoms')
    # drop consultations FKs to medical tables before removing those tables
    op.drop_constraint(op.f('consultations_department_id_fkey'), 'consultations', type_='foreignkey')
    op.drop_constraint(op.f('consultations_patient_id_fkey'), 'consultations', type_='foreignkey')
    op.drop_table('departments')
    op.drop_index(op.f('ix_patients_name'), table_name='patients')
    op.drop_table('patients')
    op.add_column('consultations', sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户 ID'))
    op.add_column('consultations', sa.Column('channel_id', sa.BigInteger(), nullable=True, comment='推荐维权渠道 ID'))
    op.add_column('consultations', sa.Column('issue_description', sa.Text(), nullable=True, comment='用户诉求描述（对标 chief_complaint）'))
    op.add_column('consultations', sa.Column('legal_advice', sa.Text(), nullable=True, comment='法律建议结论（对标 diagnosis）'))
    op.add_column('consultations', sa.Column('action_plan', sa.Text(), nullable=True, comment='行动方案 JSON（对标 prescription）'))
    op.alter_column('consultations', 'urgency_level',
               existing_type=sa.VARCHAR(length=20),
               comment='紧急程度：normal / urgent / emergency',
               existing_comment='紧急程度：normal=普通 / urgent=较急 / emergency=紧急',
               existing_nullable=False)
    op.alter_column('consultations', 'session_id',
               existing_type=sa.VARCHAR(length=100),
               comment='关联 Redis 会话 ID',
               existing_comment='关联的 Redis 会话 ID',
               existing_nullable=True)
    op.drop_index(op.f('ix_consultations_department'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_patient'), table_name='consultations')
    op.create_index('ix_consultations_channel', 'consultations', ['channel_id'], unique=False)
    op.create_index('ix_consultations_user', 'consultations', ['user_id'], unique=False)
    op.create_foreign_key(None, 'consultations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'consultations', 'channels', ['channel_id'], ['id'], ondelete='SET NULL')
    op.drop_column('consultations', 'patient_id')
    op.drop_column('consultations', 'chief_complaint')
    op.drop_column('consultations', 'department_id')
    op.drop_column('consultations', 'diagnosis')
    op.drop_column('consultations', 'prescription')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultations', sa.Column('prescription', sa.TEXT(), autoincrement=False, nullable=True, comment='处方内容（JSON 字符串）'))
    op.add_column('consultations', sa.Column('diagnosis', sa.TEXT(), autoincrement=False, nullable=True, comment='诊断结论'))
    op.add_column('consultations', sa.Column('department_id', sa.BIGINT(), autoincrement=False, nullable=True, comment='就诊科室 ID'))
    op.add_column('consultations', sa.Column('chief_complaint', sa.TEXT(), autoincrement=False, nullable=True, comment='主诉（患者自述症状）'))
    op.add_column('consultations', sa.Column('patient_id', sa.BIGINT(), autoincrement=False, nullable=False, comment='患者 ID'))
    op.drop_constraint(None, 'consultations', type_='foreignkey')
    op.drop_constraint(None, 'consultations', type_='foreignkey')
    op.create_foreign_key(op.f('consultations_patient_id_fkey'), 'consultations', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('consultations_department_id_fkey'), 'consultations', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_consultations_user', table_name='consultations')
    op.drop_index('ix_consultations_channel', table_name='consultations')
    op.create_index(op.f('ix_consultations_patient'), 'consultations', ['patient_id'], unique=False)
    op.create_index(op.f('ix_consultations_department'), 'consultations', ['department_id'], unique=False)
    op.alter_column('consultations', 'session_id',
               existing_type=sa.VARCHAR(length=100),
               comment='关联的 Redis 会话 ID',
               existing_comment='关联 Redis 会话 ID',
               existing_nullable=True)
    op.alter_column('consultations', 'urgency_level',
               existing_type=sa.VARCHAR(length=20),
               comment='紧急程度：normal=普通 / urgent=较急 / emergency=紧急',
               existing_comment='紧急程度：normal / urgent / emergency',
               existing_nullable=False)
    op.drop_column('consultations', 'action_plan')
    op.drop_column('consultations', 'legal_advice')
    op.drop_column('consultations', 'issue_description')
    op.drop_column('consultations', 'channel_id')
    op.drop_column('consultations', 'user_id')
    op.create_table('diseases',
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False, comment='疾病名称'),
    sa.Column('department_id', sa.BIGINT(), autoincrement=False, nullable=True, comment='所属科室 ID'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='疾病描述/定义'),
    sa.Column('cause', sa.TEXT(), autoincrement=False, nullable=True, comment='病因'),
    sa.Column('prevent', sa.TEXT(), autoincrement=False, nullable=True, comment='预防措施'),
    sa.Column('cure_way', sa.TEXT(), autoincrement=False, nullable=True, comment='治疗方式，多种方式用逗号分隔'),
    sa.Column('cure_lasttime', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='治疗周期，如：1-2个月'),
    sa.Column('cured_prob', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='治愈概率，如：95%'),
    sa.Column('easy_get', sa.TEXT(), autoincrement=False, nullable=True, comment='易感人群描述'),
    sa.Column('cost_money', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='参考费用区间'),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('diseases_department_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('diseases_pkey')),
    sa.UniqueConstraint('name', name=op.f('diseases_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_diseases_name'), 'diseases', ['name'], unique=False)
    op.create_table('patients',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='患者姓名'),
    sa.Column('gender', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='性别：男/女'),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True, comment='年龄'),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='联系电话'),
    sa.Column('id_card', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='身份证号（脱敏存储）'),
    sa.Column('allergy_history', sa.TEXT(), autoincrement=False, nullable=True, comment='过敏史，多种用逗号分隔'),
    sa.Column('medical_history', sa.TEXT(), autoincrement=False, nullable=True, comment='既往病史'),
    sa.Column('blood_type', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='血型，如：A/B/O/AB'),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('patients_pkey'))
    )
    op.create_index(op.f('ix_patients_name'), 'patients', ['name'], unique=False)
    op.create_table('disease_drugs',
    sa.Column('disease_id', sa.BIGINT(), autoincrement=False, nullable=False, comment='疾病 ID'),
    sa.Column('drug_id', sa.BIGINT(), autoincrement=False, nullable=False, comment='药品 ID'),
    sa.Column('relation_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='关系类型：common=常用药 / recommend=推荐药'),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], name=op.f('disease_drugs_disease_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], name=op.f('disease_drugs_drug_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('disease_drugs_pkey'))
    )
    op.create_index(op.f('ix_disease_drugs_drug'), 'disease_drugs', ['drug_id'], unique=False)
    op.create_index(op.f('ix_disease_drugs_disease'), 'disease_drugs', ['disease_id'], unique=False)
    op.create_table('departments',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='科室名称，如：内科、外科'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='科室简介'),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('departments_pkey')),
    sa.UniqueConstraint('name', name=op.f('departments_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('symptoms',
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False, comment='症状名称，如：发热、头痛'),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('symptoms_pkey')),
    sa.UniqueConstraint('name', name=op.f('symptoms_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_symptoms_name'), 'symptoms', ['name'], unique=False)
    op.create_table('disease_symptoms',
    sa.Column('disease_id', sa.BIGINT(), autoincrement=False, nullable=False, comment='疾病 ID'),
    sa.Column('symptom_id', sa.BIGINT(), autoincrement=False, nullable=False, comment='症状 ID'),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], name=op.f('disease_symptoms_disease_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptoms.id'], name=op.f('disease_symptoms_symptom_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('disease_symptoms_pkey'))
    )
    op.create_index(op.f('ix_disease_symptoms_symptom'), 'disease_symptoms', ['symptom_id'], unique=False)
    op.create_index(op.f('ix_disease_symptoms_disease'), 'disease_symptoms', ['disease_id'], unique=False)
    op.create_table('drugs',
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False, comment='药品通用名'),
    sa.Column('alias', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='别名/商品名，多个用逗号分隔'),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='药品分类，如：抗生素、解热镇痛'),
    sa.Column('manufacturer', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='生产厂家'),
    sa.Column('approval_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='国药准字批准文号'),
    sa.Column('is_otc', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否为非处方药（OTC）'),
    sa.Column('stock_quantity', sa.INTEGER(), autoincrement=False, nullable=True, comment='库存数量（运营统计用）'),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='参考零售价（元）'),
    sa.Column('expire_date', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='有效期至，格式：YYYY-MM-DD'),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('drugs_pkey'))
    )
    op.create_index(op.f('ix_drugs_name'), 'drugs', ['name'], unique=False)
    op.create_index(op.f('ix_drugs_category'), 'drugs', ['category'], unique=False)
    op.create_table('drug_details',
    sa.Column('drug_id', sa.BIGINT(), autoincrement=False, nullable=False, comment='关联药品 ID'),
    sa.Column('indication', sa.TEXT(), autoincrement=False, nullable=True, comment='适应症/功能主治'),
    sa.Column('usage_dosage', sa.TEXT(), autoincrement=False, nullable=True, comment='用法用量'),
    sa.Column('adverse_reaction', sa.TEXT(), autoincrement=False, nullable=True, comment='不良反应'),
    sa.Column('contraindication', sa.TEXT(), autoincrement=False, nullable=True, comment='禁忌症'),
    sa.Column('precaution', sa.TEXT(), autoincrement=False, nullable=True, comment='注意事项'),
    sa.Column('interaction', sa.TEXT(), autoincrement=False, nullable=True, comment='药物相互作用（文本描述，结构化关系在 Neo4j）'),
    sa.Column('storage', sa.TEXT(), autoincrement=False, nullable=True, comment='储存条件'),
    sa.Column('full_instruction', sa.TEXT(), autoincrement=False, nullable=True, comment='完整说明书原文（RAG 切片用）'),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='创建时间'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], name=op.f('drug_details_drug_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('drug_details_pkey')),
    sa.UniqueConstraint('drug_id', name=op.f('drug_details_drug_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index('ix_law_cases_law', table_name='law_cases')
    op.drop_index('ix_law_cases_case', table_name='law_cases')
    op.drop_table('law_cases')
    op.drop_index('ix_articles_no', table_name='articles')
    op.drop_index('ix_articles_law', table_name='articles')
    op.drop_table('articles')
    op.drop_index('ix_users_name', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_legal_cases_source', table_name='legal_cases')
    op.drop_index('ix_legal_cases_domain', table_name='legal_cases')
    op.drop_table('legal_cases')
    op.drop_index('ix_laws_title', table_name='laws')
    op.drop_index('ix_laws_domain', table_name='laws')
    op.drop_table('laws')
    op.drop_index('ix_channels_region', table_name='channels')
    op.drop_index('ix_channels_domain', table_name='channels')
    op.drop_table('channels')
    # ### end Alembic commands ###
